-- MIGRATION SCRIPT
-- Database Type: DBType{type='mysql', urlScheme='jdbc:', dialect='org.hibernate.dialect.MySQLDialect', driverClass='com.mysql.jdbc.Driver'}
-- App Name: Projagain2
-- Database: TestDBMaria
-- Created At: 24-Apr-2019 14:41:11.UTC
-- Script Version: 1.1
-- -----------------------------------------------------------------
-- USER SQL SCRIPT